# Generated by Django 4.0.1 on 2022-01-06 16:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('link', models.URLField()),
                ('slug', models.SlugField(blank=True, max_length=500, null=True, unique_for_date='publish')),
                ('media_house', models.CharField(blank=True, max_length=250, null=True)),
                ('description', models.TextField(blank=True, max_length=600, null=True)),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('developing', models.BooleanField(default=False)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('guid', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='publish', max_length=10)),
                ('story_category', models.CharField(choices=[('general', 'General'), ('social_news', 'Social News'), ('auto_news', 'Auto News'), ('technology', 'Technology'), ('business', 'Business'), ('education', 'Education'), ('health', 'Health'), ('life', 'Life'), ('sports', 'Sports'), ('crime', 'Crime'), ('cryptocurrency', 'Cryptocurrency'), ('entertainment', 'Entertainment'), ('national', 'National'), ('politics', 'Politics'), ('climate', 'Climate'), ('science', 'Science'), ('world', 'World'), ('videos', 'Videos')], default='general', max_length=100)),
                ('story_type', models.CharField(choices=[('featured', 'Featured'), ('trending', 'Trending'), ('breaking_story', 'Breaking Story'), ('top_story', 'Top Story'), ('developing', 'Developing'), ('normal', 'Normal')], default='normal', max_length=100)),
            ],
            options={
                'ordering': ('-publish',),
            },
        ),
    ]
