# Generated by Django 4.0.1 on 2022-01-06 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_post_country_alter_post_media_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='subregion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
